document_management/config/routes.rb
Rails.application.routes.draw do
  resources :documents

end

document_management/app/models/document.rb
class Document < ActiveRecord::Base
end

document_management/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

document_management/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to @document, notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:name, :content)
    end
end

document_management/app/helpers/application_helper.rb
module ApplicationHelper
end

document_management/app/helpers/documents_helper.rb
module DocumentsHelper
end

document_management/app/views/documents/_form.html.erb
<%= form_for(@document) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

document_management/app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form' %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

document_management/app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Documents</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <tr>
        <td><%= document.name %></td>
        <td><%= document.content %></td>
        <td><%= link_to 'Show', document %></td>
        <td><%= link_to 'Edit', edit_document_path(document) %></td>
        <td><%= link_to 'Destroy', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_document_path %>

document_management/app/views/documents/new.html.erb
<h1>New Document</h1>

<%= render 'form' %>

<%= link_to 'Back', documents_path %>

document_management/app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @document.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @document.content %>
</p>

<%= link_to 'Edit', edit_document_path(@document) %> |
<%= link_to 'Back', documents_path %>

document_management/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudentManagement</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>